CREATE TABLE escolas_alunos AS
SELECT 
    e.DRE,
    e.TIPOESC,
    e.NOMESC,
    e.NOMESCOF,
    e.CEU,
    e.DIRETORIA,
    e.SUBPREF,
    e.ENDERECO,
    e.NUMERO,
    e.BAIRRO,
    e.CEP,
    e.TEL1,
    e.TEL2,
    e.FAX,
    e.SITUACAO,
    e.CODDIST,
    e.DISTRITO,
    e.SETOR,
    e.CODINEP,
    e.CODCIE,
    e.EH,
    e.FX_ETARIA,
    e.DT_CRIACAO,
    e.ATO_CRIACAO,
    e.DOM_CRIACAO,
    e.DT_INI_FUNC,
    e.DT_INI_CONV,
    e.DT_AUTORIZA,
    e.DT_EXTINCAO,
    e.NOME_ANT,
    e.REDE,
    e.LATITUDE,
    e.LONGITUDE,
    e.DATABASE,
    e.ANO,
    a.CODESC,  
    a.SEXO,
    a.IDADE,
    a.NEE,
    a.RACA,
    a.QTDE
FROM escolas_full e
JOIN alunos_full a
ON e.CODESC = a.CODESC AND e.ANO = a.ANO;
